TiendaIna.Web.Razor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TiendaIna.Web.Razor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorViewModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorViewModel> _logger;

        public ErrorViewModel(ILogger<ErrorViewModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

TiendaIna.Web.Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using TiendaIna.Core.Model;
using TiendaIna.Core.Services;

namespace TiendaIna.Web.Razor.Pages
{
    public class IndexViewModel : PageModel
    {
        private readonly ILogger<IndexViewModel> _logger;
        private readonly IProductsService _productsService;

        #region Ctor
        public IndexViewModel(ILogger<IndexViewModel> logger, IProductsService productsService)
        {
            _logger = logger;
            _productsService = productsService;
        }
        #endregion

        #region Propertys
        public List<ProductModel> Products { get; set; }
        #endregion


        public async Task OnGetAsync()
        {
            Products = await _productsService.GetProducts();

        }

    }
}

TiendaIna.Web.Razor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TiendaIna.Web.Razor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

TiendaIna.Web.Razor/Pages/SobreNosotros.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TiendaIna.Web.Razor.Pages
{
    public class SobreNosotrosViewModel : PageModel
    {
        private readonly ILogger<SobreNosotrosViewModel> _logger;

        public SobreNosotrosViewModel(ILogger<SobreNosotrosViewModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

TiendaIna.Web.Razor/ViewComponents/ProductBoxSaleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TiendaIna.Core.Entities;
using TiendaIna.Core.Model;
using TiendaIna.Web.Razor.Pages;

namespace TiendaIna.Web.Razor.ViewComponents;
public class ProductBoxSaleViewComponent : ViewComponent {
    public IViewComponentResult Invoke(ProductModel product) {
        var model = new ProductBoxSaleViewModel(product);
        return View("ProductBoxSale", model);
    }
}

TiendaIna.Web.Razor/ViewComponents/ProductBoxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TiendaIna.Core.Entities;
using TiendaIna.Core.Model;
using TiendaIna.Web.Razor.Pages;

namespace TiendaIna.Web.Razor.ViewComponents;
public class ProductBoxViewComponent : ViewComponent {
    public IViewComponentResult Invoke(ProductModel product, bool showCategories) {
        var model = new ProductBoxViewModel(product, showCategories);
        return View("ProductBox", model);
    }
}

TiendaIna.Web.Razor/ViewComponents/ProductDetailViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TiendaIna.Core.Entities;
using TiendaIna.Core.Model;
using TiendaIna.Web.Razor.Pages;

namespace TiendaIna.Web.Razor.ViewComponents;
public class ProductDetailViewComponent : ViewComponent {
    public IViewComponentResult Invoke(ProductModel product) {
        var model = new ProductDetailViewModel(product);
        return View("ProductDetail", model);
    }
}

TiendaIna.Web.Razor/Pages/Index.cshtml
@page
@using TiendaIna.Core.Entities
@using TiendaIna.Core.Models
@using TiendaIna.Core.Services
@model IndexViewModel
@{
    ViewData["Title"] = "INICIO";
}

<div class="container-fluid">
    <div class="row">

            @*Prueba ofertas semanales*@
            <div class="alert alert-dark custom-alertSale text-center" role="alert">
                🔥 OFERTAS SEMANALES 🔥
            </div>

            @*ofertas*@
            <div class="row justify-content-center fondo-ofertas py-4">
                @if (Model.Products != null && Model.Products.Any(p => p.IsOutstanding == true)) {
                    @foreach (var p in Model.Products.Where(p => p.IsOutstanding == true).Take(3)) {
                        <div class="col-12 col-md-4 mb-4">
                            <vc:product-box-sale product="@p"></vc:product-box-sale>
                        </div>
                    }
                } else {
                    <div class="text-center text-white">
                        <p>No hay ofertas destacadas en este momento.</p>
                    </div>
                }
            </div>

            @*CARTEL DE PRESENTACION PRODUCTOS*@
            <div class="alert alert-dark custom-alert" role="alert" mt-2 
            >
                NUESTROS PRODUCTOS
            </div>


            @*TABLAS PRODUCTOS VISTA PREVIA*@

            <div class="row">
                @foreach (var p in @Model.Products) {
                    <div class="col-6 col-md-4 mb-4">
                        <vc:product-box product="@p" show-categories="true"></vc:product-box>
                    </div>
                }
            </div>
            @*Agregar paginacion de productos*@
    </div>
</div>

TiendaIna.Web.Razor/Pages/Product.cshtml
@page "/Product/{id:int}"
@model ProductViewModel

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <vc:product-detail product="@Model.Product"></vc:product-detail>
        </div>
    </div>
</div>

TiendaIna.Web.Razor/Pages/SobreNosotros.cshtml
@page
@model SobreNosotrosViewModel
@{
    ViewData["Title"] = "Sobre Nosotros";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>